version: "3"

services:
  db.auth.session:
    image: mongo:mis.db.auth.session.pdn
    restart: always
    container_name: mis.db.auth.session.pdn
  db.auth.main:
    image: mariadb:mis.db.auth.main.pdn
    restart: always
    container_name: mis.db.auth.main.pdn
    volumes:
    - /usr/src/mis/auth/db/data/dump:/var/tmp/dump
    - /usr/src/mis/auth/db/config/docker.extra.cnf:/etc/mysql/conf.d/docker.extra.cnf
  db.app.main:
    image: mariadb:mis.db.main.pdn
    restart: always
    container_name: mis.db.main.pdn
    volumes:
      - /usr/src/mis/main/db/data/dump:/var/tmp/dump
      - /usr/src/mis/main/db/config/docker.extra.cnf:/etc/mysql/conf.d/docker.extra.cnf
  db.app.msa:
    image: mariadb:mis.db.msa.pdn
    restart: always
    container_name: mis.db.msa.pdn
    volumes:
      - /usr/src/mis/msa/db/data/dump:/var/tmp/dump
      - /usr/src/mis/msa/db/config/docker.extra.cnf:/etc/mysql/conf.d/docker.extra.cnf
  app.auth:
    image: node:mis.server.auth.pdn
    restart: always
    container_name: mis.server.auth.pdn
    depends_on:
      - db.auth.session
      - db.auth.main
    ports:
    - 8202:3000
    volumes:
    - /usr/src/mis/auth/app/app_modules/dist:/usr/src/app/app_modules/dist
  app.main:
    image: node:mis.server.main.pdn
    restart: always
    container_name: mis.server.main.pdn
    depends_on:
      - db.app.main
    ports:
      - 8203:3000
    volumes:
      - /usr/src/mis/main/app/app_modules/dist:/usr/src/app/app_modules/dist
  app.msa:
    image: node:mis.server.msa.pdn
    restart: always
    container_name: mis.server.msa.pdn
    depends_on:
      - db.app.msa
    ports:
      - 8204:3000
    volumes:
      - /usr/src/mis/msa/app/app_modules/dist:/usr/src/app/app_modules/dist