export default [
    {
        name_last:              'Мурасова',
        name_first:             'Людмила',
        name_patronymic:        'Алексеевна',
        position:               'врач-терапевт высшей квалификационной категории',
        department:             'Поликлинка',
        submissionLevel:        'заведующий поликлиникой',
    },
    {
        name_last:              'Дмитренко',
        name_first:             'Светлана',
        name_patronymic:        'Викторовна',
        position:               'врач-онколог высшей квалификационной категории',
        department:             'Отдел экспертизы качества медицинской помощи',
        submissionLevel:        'заведующий отделом экспертизы качества медицинской помощи',
    },
    {
        name_last:              'Мельникова',
        name_first:             'Светлана',
        name_patronymic:        'Григорьевна',
        position:               'врач-терапевт высшей квалификационной категории',
        department:             'Терапевтическое отделение',
        submissionLevel:        'заведующий терапевтическим отделением',
    },
    {
        name_last:              'Радионова',
        name_first:             'Наталья',
        name_patronymic:        'Владимировна',
        position:               'врач-кардиолог, высшая категория',
        department:             'кардиологический кабинет',
        submissionLevel:        '',
    },
    {
        name_last:              'Табак',
        name_first:             'Анна',
        name_patronymic:        'Анатольевна',
        position:               'врач-кардиолог, вторая категория',
        department:             'кардиологический кабинет',
        submissionLevel:        '',
    },
    {
        name_last:              'Миселёва',
        name_first:             'Вера',
        name_patronymic:        'Петровна',
        position:               'врач-эндокринолог, высшая категория',
        department:             'эндокринологический кабинет',
        submissionLevel:        '',
    },
    {
        name_last:              'Ионова',
        name_first:             'Наталья',
        name_patronymic:        'Олеговна',
        position:               'врач-нарколог, высшая категория',
        department:             'наркологический кабинет',
        submissionLevel:        '',
    },
    {
        name_last:              'Гафантулина',
        name_first:             'Элина',
        name_patronymic:        'Викторовна',
        position:               'врач-хирург, высшая категория',
        department:             'отделение амбулаторной хирургии',
        submissionLevel:        'заведующий отделением амбулаторной хирургии',
    },
];